#!/bin/bash
#-----------------------------------------------------------
#   Function    : fnDeploy
#   Date        : 02/08/2018
#   Objetive    : Deploy from GitHub
#   Parameters  : (opt) put "-y" to acept all the questions
#
#   Exaple      : fnDeploy
#-------------------------------------------------Modules
source modGeneral
source $G_SCRIPTS_PATH/prcCrearAccesos.conf
#-------------------------------------------------Variables
l_strLinksPath=/usr/bin
l_strLinkList=(${l_strLinkList})
#-------------------------------------------------Functions

#-------------------------------------------------Main
ShowHeader " Create Links Started..."

ShowMessage " - Deleting previous links if exist..."
if [ $(ls $l_strLinksPath/fn* | wc -l) -gt 0 ]; then
	sudo rm $l_strLinksPath/fn*
	sudo rm $l_strLinksPath/mod* $l_strLinksPath/var*
fi

ShowMessage " - Creating links into: $l_strLinksPath"
for index in ${!l_strLinkList[*]}
do
    ShowMessage " - Creating: ${l_strLinkList[index]}"
	sudo ln -s $G_SCRIPTS_PATH/${l_strLinkList[index]} $l_strLinksPath/${l_strLinkList[index]}
done

ShowMessage " Create Links terminated successfully!!"

