#!/bin/bash
#-----------------------------------------------------------
#   Function    : varGeneral
#   Date        : 16/05/2018
#   Objetive    : General variables to be used in other scripts
#   Parameters  : N/A
#
#   Exaple      : source varGeneral
#-------------------------------------------------Variables

G_PROG_NAME=$(basename $0)                                         			#Nombre del Script que esta ejecutando
G_FORMAT_DATE="%d%m%Y"                                          			#Almacena la fecha
G_FORMAT_TIMESTAMP="%d/%m/%Y %H:%M:%S"                         				#Almacena fecha, hora y min
G_LOG_PATH=~/.logs	                         								#Carpeta de Logs
G_LOG_FILE=$G_PROG_NAME.csv                          						#Nombre Archivo Log
G_PROCESS=""																#Para definir en que parte del proceso esta un script
G_AVOID_ERROR=0																#Variable para evitar algunos errores cuando se ejecutan scripts