#!/bin/bash
#-----------------------------------------------------------
#   Function    : fnUpdate
#   Date        : 02/08/2015
#   Objetive    : Install Updates
#   Parameters  : (opt) put "-y" to acept all the questions
#
#   Exaple      : fnUpdate -y
#-------------------------------------------------Modules
source modGeneral
#-------------------------------------------------Variables

#-------------------------------------------------Functions

#-------------------------------------------------Main
ShowHeader "Update Started..."

LogMessage "Executing: sudo dnf update $*"
sudo dnf update $*

G_AVOID_ERROR=1
LogMessage "Executing: sudo pkcon update $*"
sudo pkcon update $*

G_AVOID_ERROR=0
ShowHeader "Updated Succesfully..."
