#!/bin/bash

#-----------------------------------------------------------
#   Function    : compress-archive
#   Date        : 25/06/2022
#   Objetive    : Compress a File or Folder acording to the extension. Standard = 7z.
#   Parameters  : source_path
#                 target
#
#   Example      : compress-archive "Path File/Folder" "Path to store/File Name.zip"
#-----------------------------------------------------------
source_path="$1"
target="$2"
default_ext="7z"

if [[ $(test-file $source_path) = true || $(test-folder $source_path) = true ]]; then

    tmp_name=$(file-getname "$source_path")
    tmp_ext=$(file-getextension "$tmp_name")

    # if no target provided
    if [ $(string-isempty "$target") = true ]; then
        target=$(string-replace "$tmp_name" ".$tmp_ext" ".$default_ext")
    # if target provided but no extension
    elif [ $(string-isempty "$(file-getextension "$target")" ) = true ]; then
        target="$target/$(string-replace "$tmp_name" ".$tmp_ext" ".$default_ext")"
    fi

    case $target in
            # *.tar.bz2)
            #     #tar xjf $1
            #     ;;
            # *.tar.gz)
            #     #tar xzf $1
            #     ;;
            # *.bz2)
            #     #bunzip2 $1
            #     ;;
            # *.rar)
            #     #rar x $1
            #     ;;
            # *.gz)
            #     #gunzip $1
            #     ;;
            # *.tar)
            #     #tar xf $1
            #     ;;
            # *.tbz2)
            #     #tar xjf $1
            #     ;;
            # *.tgz)
            #     #tar xzf $1
            #     ;;
            # *.zip)
            #     #unzip $1
            #     ;;
            # *.Z)
            #     #uncompress $1
            #     ;;
            *.7z)
                7z a $target $source_path
                ;;
            *)
                echo "Error: Invalid target extension = '$target'"
                exit 1
                ;;
        esac

else
    echo "Error: Invalid source = '$source_path'"
    exit 1
fi