#!/bin/bash

#-----------------------------------------------------------
#   Function    : file-getname
#   Date        : 28/06/2022
#   Objetive    : Gets file name and extension from a given path
#   Parameters  : file_path
#
#   Example     : variable=$(file-getname "path/to/the/file/name.ext")
#-----------------------------------------------------------
file_path="$1"

if [ $(string-isempty "$file_path") != true ];then
    echo "$(basename $file_path)"
else
    echo ""
fi