#!/bin/bash

#-----------------------------------------------------------
#   Function    : string-right
#   Date        : 27/06/2022
#   Objetive    : Return right number of characteres of a string
#   Parameters  : original_string
#
#   Example     : string-right "Original string" 6
#-----------------------------------------------------------

original_string="$1"
positions="$2"

echo ${original_string:(-$positions)}