#!/bin/bash

#-----------------------------------------------------------
#   Function    : string-split
#   Date        : 26/06/2022
#   Objetive    : Splits a string by a given char and creates a variable with array
#               : It needs to be ran in current shell by run like:
#                   source string-split []
#               or  . string-split []
#   Parameters  : string
#                 separator
#                 new_var_name
#                 new_var_count
#
#   Example 1   : string-split "String|to|split" "|" "array_variable_name" "count_variable_name"    <= it returns a string
#   Example 2   : echo ${variable[0]}                                                               <= access items
#               : echo ${#variable[*]}                                                              <= get number of elements
#               : echo ${!variable[*]}                                                              <= get list of indexes
#-----------------------------------------------------------

SplitString()
{
    local string="$1"
    local separator="$2"
    local new_var_name="$3"
    local new_var_count="$4"
    local OIFS=$IFS

    local array_result

    IFS=$separator
    array_result=(${string})

    eval $new_var_name='(${array_result[*]})'

    if [ "$new_var_count" != "" ]; then
        eval $new_var_count='${#array_result[*]}'
    fi

    IFS=$OIFS
}

SplitString "$@"