#!/bin/bash

#-----------------------------------------------------------
#   Function    : test-file
#   Date        : 23/06/2022
#   Objetive    : Validate whether a file exists.
#   Parameters  : file_path
#
#   Example      : variable=$(test-file "path/to/the/file")
#-----------------------------------------------------------
file_path="$1"
    
if [ -f "$file_path" ]; then
    echo true
else
    echo false
fi