#!/bin/bash

#-----------------------------------------------------------
#   Function    : test-folder
#   Date        : 23/06/2022
#   Objetive    : Validate whether a folder exists.
#   Parameters  : folder_path
#
#   Example      : variable=$(test-folder "path/to/the/folder")
#-----------------------------------------------------------
folder_path="$1"
    
if [ -d "$folder_path" ]; then
    echo true
else
    echo false
fi